#!/bin/bash

mkdir -p /etc/msu-manager
mkdir -p /opt/msu-manager

useradd -M msumanager
usermod -L msumanager

mkdir -p /etc/sudoers.d

cat <<EOF >/etc/sudoers.d/msu-manager
msumanager ALL=(ALL) NOPASSWD: /sbin/shutdown, /sbin/reboot, /sbin/poweroff
EOF

chmod 440 /etc/sudoers.d/msu-manager