#!/bin/bash

mkdir -p /etc/msu-manager
mkdir -p /opt/msu-manager

useradd -M msumanager
usermod -L msumanager

mkdir -p /etc/sudoers.d

cat <<EOF >/etc/sudoers.d/msu-manager
# Allow msumanager to run shutdown and pass environment variables to lte-connect.sh
Defaults!/usr/bin/bash env_keep += "DEVICE_ID APN WWAN_IFACE"
msumanager ALL= NOPASSWD: /usr/sbin/shutdown -h now, /usr/bin/bash /usr/bin/lte-connect.sh
EOF

chmod 440 /etc/sudoers.d/msu-manager