name: Create release

on:
  workflow_dispatch:
    inputs:
      versionChoice:
        type: choice
        required: true
        description: Version Change
        options:
        - patch
        - minor
        - major

permissions:
  contents: write

env:
  IMAGE_NAME: power-toggle-service
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg
  REPO_URL: https://Starwit:$GITHUB_TOKEN@github.com/starwit/power-toggle-service.git

jobs:
  create-release:
    name: create new release
    runs-on: [self-hosted, linux, X64]
    container:
      image: starwitorg/debian-packaging:0.0.3
      volumes:
        - /home/githubrunner/.cache/pypoetry:/root/.cache/pypoetry
      env:
        PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD_FLAT }}
        GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY_B64 }}

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1        
        
      - name: create new version in pyproject.toml
        run: |
          poetry version $VERSION
        env:
          VERSION: ${{ inputs.versionChoice }}

      - name: get last commit message and update APT changelog
        run: |
          RELEASE_MSG="$(git log -1 --pretty=%B)"
          echo $RELEASE_MSG
          bash -c "export RELEASEMSG=$RELEASE_MSG; make set-version"
          cat debian/changelog

      - name: commit new version
        run: |
          git status
          git config --global user.email "code@starwit.de"
          git config --global user.name "Starwit"
          git remote set-url --push origin $REPO_URL
          git add .
          modifications=$(git status | grep "modified" || true)
          if [ ! -z "$modifications" ]
          then
            echo "modifications found: $modifications"
            git commit -m "modified project version" ./pyproject.toml ./debian/changelog
            git push
          fi 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build apt package
        run: |
            echo "Build APT package"
            bash -c "poetry self add poetry-plugin-export; make build-deb"
            echo "Finish building APT package"

      - name: Create github release
        run: | 
          APP_VERSION=$(cat pyproject.toml | grep "version" | cut -d'=' -f2 | xargs echo -n) 
          gh release create $APP_VERSION -F README.md --title "${APP_VERSION}" --target $(git branch --show-current) ./target/*deb ./target/*.dsc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
